// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ExtractWizard.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ExtractWizard.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BTN_BROWSE_ARCHIVE {
            get {
                return ResourceManager.GetString("BTN_BROWSE_ARCHIVE", resourceCulture);
            }
        }
        
        internal static string BTN_BROWSE_FOLDER {
            get {
                return ResourceManager.GetString("BTN_BROWSE_FOLDER", resourceCulture);
            }
        }
        
        internal static string BTN_CANCEL {
            get {
                return ResourceManager.GetString("BTN_CANCEL", resourceCulture);
            }
        }
        
        internal static string BTN_EXTRACT {
            get {
                return ResourceManager.GetString("BTN_EXTRACT", resourceCulture);
            }
        }
        
        internal static string BTN_HELP {
            get {
                return ResourceManager.GetString("BTN_HELP", resourceCulture);
            }
        }
        
        internal static string BTN_OPEN {
            get {
                return ResourceManager.GetString("BTN_OPEN", resourceCulture);
            }
        }
        
        internal static string BTN_SELECT {
            get {
                return ResourceManager.GetString("BTN_SELECT", resourceCulture);
            }
        }
        
        internal static string BTN_CANCELDIALOG {
            get {
                return ResourceManager.GetString("BTN_CANCELDIALOG", resourceCulture);
            }
        }
        
        internal static string CHK_DRY_RUN {
            get {
                return ResourceManager.GetString("CHK_DRY_RUN", resourceCulture);
            }
        }
        
        internal static string CHK_IGNORE_ERRORS {
            get {
                return ResourceManager.GetString("CHK_IGNORE_ERRORS", resourceCulture);
            }
        }
        
        internal static string GROUP_OPTIONS {
            get {
                return ResourceManager.GetString("GROUP_OPTIONS", resourceCulture);
            }
        }
        
        internal static string GROUP_PROGRESS {
            get {
                return ResourceManager.GetString("GROUP_PROGRESS", resourceCulture);
            }
        }
        
        internal static string LBL_BACKUP_ARCHIVE {
            get {
                return ResourceManager.GetString("LBL_BACKUP_ARCHIVE", resourceCulture);
            }
        }
        
        internal static string LBL_CANCEL_BODY {
            get {
                return ResourceManager.GetString("LBL_CANCEL_BODY", resourceCulture);
            }
        }
        
        internal static string LBL_CANCEL_CAPTION {
            get {
                return ResourceManager.GetString("LBL_CANCEL_CAPTION", resourceCulture);
            }
        }
        
        internal static string LBL_ERROR_CAPTION {
            get {
                return ResourceManager.GetString("LBL_ERROR_CAPTION", resourceCulture);
            }
        }
        
        internal static string LBL_EXTRACT_TO {
            get {
                return ResourceManager.GetString("LBL_EXTRACT_TO", resourceCulture);
            }
        }
        
        internal static string LBL_PASSWORD {
            get {
                return ResourceManager.GetString("LBL_PASSWORD", resourceCulture);
            }
        }
        
        internal static string LBL_SUCCESS_BODY {
            get {
                return ResourceManager.GetString("LBL_SUCCESS_BODY", resourceCulture);
            }
        }
        
        internal static string LBL_SUCCESS_CAPTION {
            get {
                return ResourceManager.GetString("LBL_SUCCESS_CAPTION", resourceCulture);
            }
        }
        
        internal static string LBL_FILETYPE_JPA {
            get {
                return ResourceManager.GetString("LBL_FILETYPE_JPA", resourceCulture);
            }
        }
        
        internal static string LBL_FILETYPE_JPS {
            get {
                return ResourceManager.GetString("LBL_FILETYPE_JPS", resourceCulture);
            }
        }
        
        internal static string LBL_FILETYPE_ZIP {
            get {
                return ResourceManager.GetString("LBL_FILETYPE_ZIP", resourceCulture);
            }
        }
        
        internal static string LBL_HEADER_SELECT_ARCHIVE {
            get {
                return ResourceManager.GetString("LBL_HEADER_SELECT_ARCHIVE", resourceCulture);
            }
        }
    }
}
